version: '2'
services:
  database:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=p0-g3n3r@t10n
      - POSTGRES_DATABASE=post_generation